package-lock.json
package.json
src/Dapp/dapp.js
src/DappRequests/store.js
src/SyncWarning/syncWarning.spec.js
src/index.electron.js
src/index.parity.js
src/inject.js
src/secureApi.js
src/util/token.js
webpack/inject.js
webpack/shared.js

Same as #7, besides the fact that this version only works with Electron.
Parity doesn't need to serve on :8180 anymore (cleaner UI/core split)
- Run `parity --ws-origins parity://*.wallet.parity`
- Dev: `npm start` in one terminal and `npm run electron:dev` in another
- Prod: `npm run electron`
Note: If you run `npm start`, it's still possible to dev in browser environment like before. Only built app is not browser-compatible.
- Electron can now take arguments `--ws-interface`, `--ws-port` (exactly like parity).
- Removed all uiUrl, uiApi, httpProvider, :8180... from `SecureApi`.
- UI calls `http://127.0.0.1:8546/api/ping` for isNodeUp (instead of :8180 before)
- UI doesn't do any HTTP fetch on `127.0.0.1:8180/rpc` to get `parity_wsUrl` and `parity_dappsUrl`. Instead, it takes those two …

Pure Electron MVP

---

src/Status/SignerPending/RequestItem/requestItem.js
src/Status/SignerPending/signerPending.js

Bug: when calling a signer request with `eth_sign` or `parity_decryptMessage`, the requests don't show up in the Status bar (not implemented).
This PR implements that:

Fix bug allow eth_sign and parity_decryptMessage

---

README.md
package-lock.json
package.json
src/Connection/connection.css
src/Connection/connection.js
src/index.electron.js
src/util/isParityInstalled.js
src/util/parityInstallLocation.js
src/util/promiseAny.js
webpack/app.js
webpack/electron.js

This PR does, on UI launch, the follwing
- if parity running, do nothing
- if parity installed and not running, run parity
- if parity not installed, show download instructions
To test:
1. Open UI with parity running -> Shoudl work as before
2. Don't run parity and open UI -> Should spawn a parity instance (i.e. `ps aux | grep parity` should list parity). Note: since parity is run as a child process, closing the UI will close parity as well.
3. `sudo mv /path/to/parity /path/to/parity.bak`, launch UI -> Should show download instructions

Run parity if installed

---

.travis.yml
README.md
package-lock.json
package.electron.json
package.json
src/index.electron.js
webpack/app.js

While playing with Electron installed via .dmg, I found out when parity is launched by UI, and when I close UI, parity actually doesn't stop (different behavior when using `npm run electron`). This PR forces parity to stop when electron stops.
Also rename Parity Wallet -> Parity UI.
@jacogr If you want to test this, in https://github.com/Parity-JS/shell/releases there's a draft version which contains binaries with this PR's changes. I tested on windows and osx and both works, would like you to play a bit with it too.

Fix bug parity not closed

---

package.electron.json
package.json
src/index.electron.js
src/util/windowInstaller.nsh
webpack/electron.js

- Change some leftovers parity wallet -> parity ui
- Add a script on windows to change the default install directory (was AppData/... before): now it's `C:/Program Files/Parity Technologies/Parity UI` (next to parity core)

Change windows config

---

package-lock.json
package.json
webpack/app.js
webpack/shared.js

Backport of https://github.com/paritytech/parity/pull/8093

Optimize embed size.

---

.travis.yml
package.electron.json
src/index.electron.js

- Add tar.xz on linux
- Fix windows installer per-user/per-machine bug
- Run `parity` with `--ws-origins ...`. The `You have parity 1.9.4, please install 1.10` screen wouldn't show otherwise.

Feedback fixes

---

src/Connection/connection.js
src/index.electron.js

If the UI needs token, then Electron will attempt to run `parity signer new-token` itself, and pass the generated token to the UI.
It'll save a lot of trouble of people not knowing how to run that command in the terminal.
To test: in the devtools console, run `localStorage.removeItem('sysuiToken')`, and refresh page. You should see a "Connecting to secure API directly", without the need of putting token.

Auto sign token when necessary

---

package-lock.json
package.json
src/serviceWorker.js
webpack/app.js

There are a lot of error messages due to service worker not present, and, while harmless, they tend to scare users.
This PR adds a service worker plugin to make service workers work:
- npm install --save-dev promise-worker serviceworker-webpack-plugin worker-loader
- add a (empty) service worker plugin for webpack
- also updated ref to latest plugin-signer-account (the css fix one)
To test:
- npm run electron
When electron pops up, there should be no service worker errors, but a `ServiceWorker is setup` message logged instead.
Closes https://github.com/parity-js/dapp-wallet/issues/6.

Remove console errors due to service worker

---

electron/index.js
package-lock.json
package.json
src/Dapp/dapp.js
webpack/electron.js

To test: `npm run electron`, in the wallet, in any account, click on the Etherscan link.
Also small detail, changed webpack config so that it outputs `.build/electron.js` instead of `.build/electron/index.js`. If `npm run electron` works, everything should be fine.

Fix opening external links

---

src/inject.js

Previously appId was undefined for dapps built locally that were served by Parity.
I also noticed that currently the appId for hashes can either include `0x` or not (depending on how the dapp is served); I left it this way because otherwise known dapps would have to request their permissions again (with/without `0x`), but it might be worth normalizing this at some point.

Fix appId heuristics in inject.js

---

electron/cli/index.js
package-lock.json
package.json

[BETA] Fix small bug CLI

---

package-lock.json
package.json
src/Dapp/dapp.js
src/DappRequests/RequestGroups/RequestGroups.js
src/Dapps/dapps.js
src/Dapps/dappsBuiltin.json
src/Dapps/store.js
src/Dapps/store.spec.js
src/ParityBar/parityBar.js
src/shellMiddleware.js
src/util/dapps.js
src/util/host.js
webpack/app.js

- Merge dappsViews onto dappsBuiltin
- Move dapps files from `@parity/shared` to the shell
- Fetch icons of builtin dapps from filesystem using manifest.json

Move Dapps files from @parity/shared ; display icons of builtin dapps from filesystem

---

package-lock.json
package.json
src/Dapp/dapp.js

@devops-parity pointed out [this article](https://www.trustwave.com/Resources/SpiderLabs-Blog/CVE-2018-1000136---Electron-nodeIntegration-Bypass/?_gclid=5b009a9caccdd5.68822352-5b009a9cacce59.61250057&_utm_source=xakep&_utm_campaign=mention167843&_utm_medium=inline&_utm_content=lnk739253583705) which introduces an attack vector to access all node.js capabilities if a malicious external dapp is loaded via webview.
So we:
- disable nodeintegration for all dapps (should have been disabled since the beginning)
- update electron to 2.0.2 where they fixed this issue
To be backported to stable and beta

Update to electron 2

---

package-lock.json
package.json
src/Dapps/dappsBuiltin.json
src/Dapps/store.js
src/inject.js

The wallet retains the same id (v1) as when the dapp was served by Parity, so it shouldn't ask for any new permissions.
I updated inject.js to cover the case of a fs (builtin) dapp with an id that is not a hash.
Also made it so that dapps cannot overwrite already loaded builtin dapps (to ignore the v1 `app.type === 'local'` served by Parity until it's removed from the node).
I'm sometimes getting "Uncaught Error: Provider needs to be supplied to Api instance" (in the wallet at least) or `window.require` errors; not sure why, don't think it's related to this PR.

Add dapp-wallet to built-in dapps; load it from fs

---

package-lock.json
package.json
src/Dapp/dapp.css
src/Dapp/dapp.js
src/index.electron.js
src/index.parity.ejs
src/inject.js
src/preload.js
src/util/csp.js
webpack/app.js
webpack/preload.js
webpack/shared.js

[stable] Electron security

---

electron/operations/signerNewToken.js
package-lock.json

Closes #133, also reported by @tomusdrw.
Electron runs itself `parity signer new-token` when necessary. For some reason if this commands fails, we should catch it, instead of showing the uncaught error message box.
PS: the 5k line change comes from updating package-lock.json with npm v6.

Fix eaccess bug in electron

---

package-lock.json
package.json
src/index.electron.js

[stable]  Remove preload.js path verification

---

electron/index.js
electron/utils/parityPath.js
electron/utils/paths.js
src/Dapp/dapp.js
src/Dapps/dappsBuiltin.json
src/Dapps/store.js
src/inject.js
src/util/dapps.js
src/util/host.js

Local dapps are now located in `~/.config/Parity-UI/dapps/`. Local dapps served by Parity are ignored and need to be moved to this new location.
Prevent local dapps from using the appId of a non-local dapp (for which the user might already have approved permissions): `{"id": "v1"}` is inconspicuous. Local dapps ids are now prefixed with `LOCAL-` (caps to prevent accidental use of the prefix when naming one's dapp).

Parse and load local dapps directly from filesystem

---

electron/index.js

Closes https://github.com/parity-js/shell/issues/118
* Prevent the dapp from navigating to resources outside the dapp in the same frame
* Enforce `?appId` when navigating to other files of the dapp (allows multi-page dapps to use the api; prevent appId spoofing)

Restrict in-frame navigation for dapps

---

src/secureApi.js

/api/ping will be removed when dapps gets removed from Parity.
Just tested:
- `curl -X HEAD 127.0.0.1:8546` returns something when Parity is running
- `curl -X HEAD 127.0.0.1:8546` returns nothing when Parity is off.
Working inside the UI as well, by turning on/off Parity.
@axelchalon Would like you to test too, just to be sure.

Remove call to /api/ping

---

electron/index.js

Previously we were blocking file:// requests save for requests ending with `.png`. However, this still blocked requests to network dapp icons, as their image files are stored in the filesystem without extension.

Fix network dapp icons not displaying in dapp-dapp-visible

---

src/Connection/connection.js

On all Parity UI v0.2, we need to enforce Parity version to be 1.10 or 1.11.
Reason: starting from the next Parity version (v2.0.0), the `parity_nodeHealth` rpc will be removed, so the old UI won't be compatible with the latest Parity.
Parity UI v0.3 will be compatible with all versions of Parity (>=1.10, that is).
Closes #161.

[BETA] Only allow Parity 1.10 and 1.11

---

package-lock.json
package.json
scripts/publish-snap.sh
src/Connection/connection.js

- 0.3 becomes beta
- 0.2 becomes stable
- 0.1 becomes old

[STABLE] Bump Beta to Stable

---

electron/index.js
src/util/dapps.js

Previously, `fetchParity` was called with `mainWindow` as argument but we had no guarantee that `mainWindow` was defined at that time.

Fix fetchParity(mainWindow) race condition

---

.gitlab-ci.yml
electron/index.js
package-lock.json
package.json
src/Dapp/dapp.js
src/DappRequests/store.js
src/inject.js
src/preload.js
src/shellMiddleware.js

Backport #177
* Use persistent storage for webviews
* Update .gitlab-ci.yml
enable gitsync
* Retrieve dapp token internally
* Remove shell_requestNewToken RPC method. The token must be retrieved internally (by importing DappsRequestsStore in Parity UI), this way we can be sure that the appId is coming from a trusted source. The token, along with the appId, are now passed as query string parameters to the dapp (and to subsequent pages during in-dapp navigation)
* Use new version of @parity/api stripped of shell_requestNewToken methods that are now unused
* Use synchronous blocking methods in preload.js to maximize chances of web3/parity/ethereum objects being available directly to the dapp, before its own js executes.

[BETA] Use persistent storage
